quarkus:

  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/booking_db
      driver: org.postgresql.Driver


  hibernate-orm:
    database:
      generation: none
    log:
      sql: false

  flyway:
    migrate-at-start: true
    locations: classpath:db/migration
    baseline-on-migrate: true


  http:
    port: 8081


  log:
    console:
      color: true
      enable: true
    level: INFO

  quartz:
    jdbc:
    clustered: true
    store-type: jdbc-cmt
    misfire-policy:
      task-job: ignore-misfire-policy