quarkus:

  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/payment_db
      driver: org.postgresql.Driver


  hibernate-orm:
    database:
      generation: none
    log:
      sql: false

  flyway:
    migrate-at-start: true
    locations: classpath:db/migration
    baseline-on-migrate: true


  http:
    port: 8082


  log:
    console:
      enable: true
      color: true
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [request.id=%X{request.id}] [method=%X{request.method}] [path=%X{request.path}] [query=%X{request.query}] [ip=%X{remote.addr}] [user-agent=%X{user.agent}] [%c{2.}] (%t) %s%n"
    level: INFO

  quartz:
    jdbc:
    clustered: true
    store-type: jdbc-cmt
    misfire-policy:
      task-job: ignore-misfire-policy

